{
 "title": "Hbase_new",
 "description": "Hbase in kubernetes using prometheus jmx eporter",
 "tags": [ "hbase" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(instance)" },
   { "name": "num_ops", "query": "metrics(num_ops)" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Region Servers",
   "type": "graph",
   "description": "Number of region servers managed under given namenode instance. Also allows to detect active master rnode change",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_numregionservers{instance=~\"$instance\"}",
     "legendFormat": "{{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Dead Regions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_deadserveropenregions{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Regions in transition",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_ritcount{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Exceptions rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hbase_exceptions{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ instance }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hbase_totalrequestcount{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ instance }} {{ pod }}"
    }
   ]
  },
  {
   "title": "rx/tx master",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hbase_receivedbytes{pod=~\".*master.*\",instance=~\"$instance\"}[1m])",
     "legendFormat": "rx {{ instance }} {{ pod }}"
    },
    {
     "expr": "rate(hadoop_hbase_sentbytes{pod=~\".*master.*\",instance=~\"$instance\"}[1m])",
     "legendFormat": "tx {{ instance }} {{ pod }}"
    }
   ]
  },
  {
   "title": "rx/tx region",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hbase_receivedbytes{pod=~\".*region.*\",instance=~\"$instance\"}[1m])",
     "legendFormat": "rx {{ instance }} {{ pod }}"
    },
    {
     "expr": "rate(hadoop_hbase_sentbytes{pod=~\".*region.*\",instance=~\"$instance\"}[1m])",
     "legendFormat": "tx {{ instance }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Average Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_averageload{instance=~\"$instance\"}",
     "legendFormat": "{{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Regions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "flushed cells size rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_flushedcellssize{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }} {{ pod }}"
      }
     ]
    },
    {
     "title": "read request rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_readrequestcount{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }} {{ pod }}"
      }
     ]
    },
    {
     "title": "hlog file size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_hlogfilesize{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} {{ pod }}"
      }
     ]
    },
    {
     "title": "flushed memstore rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_flushedmemstorebytes{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }} {{ pod }}"
      }
     ]
    },
    {
     "title": "flushed cells count rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_flushedcellscount{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }} {{ pod }}"
      }
     ]
    },
    {
     "title": "flushed memstore rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_flushedmemstorebytes{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }} {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "num_ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
     "repeat": "num_ops",
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 28 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 28 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 33 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 33 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 38 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 38 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 43 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 43 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 48 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 48 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 53 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 53 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 58 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 58 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 58 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 63 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 63 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 63 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 63 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "$num_ops rate",
     "type": "graph",
     "description": "Rate of number of operations ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 68 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_[[num_ops]]_num_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Java",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "jvm_memory_bytes_used",
     "type": "graph",
     "description": "Used bytes of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{instance=~\"$instance\"}",
       "legendFormat": "{{area}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_bytes_committed",
     "type": "graph",
     "description": "Committed (bytes) of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_committed{instance=~\"$instance\"}",
       "legendFormat": "{{area}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_bytes_max",
     "type": "graph",
     "description": "Max (bytes) of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_max{instance=~\"$instance\"}",
       "legendFormat": "{{area}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_bytes_init",
     "type": "graph",
     "description": "Initial bytes of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_init{instance=~\"$instance\"}",
       "legendFormat": "{{area}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_pool_bytes_used",
     "type": "graph",
     "description": "Used bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_pool_bytes_committed",
     "type": "graph",
     "description": "Committed bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_pool_bytes_max",
     "type": "graph",
     "description": "Max bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_pool_bytes_init",
     "type": "graph",
     "description": "Initial bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_init{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_buffer_pool_capacity_bytes",
     "type": "graph",
     "description": "Bytes capacity of a given JVM buffer pool.\ngauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_pool_capacity_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_buffer_pool_used_buffers",
     "type": "graph",
     "description": "Used buffers of a given JVM buffer pool.\ngauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_pool_used_buffers{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_threads_started_total",
     "type": "graph",
     "description": "Started thread count of a JVM\ncounter",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_started_total{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_threads_daemon",
     "type": "graph",
     "description": "Daemon thread count of a JVM\ngauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_threads_current",
     "type": "graph",
     "description": "Current thread count of a JVM\ngauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_threads_peak",
     "type": "graph",
     "description": "Peak thread count of a JVM\ngauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_peak{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_threads_deadlocked_monitor",
     "type": "graph",
     "description": "Cycles of JVM-threads that are in deadlock waiting to acquire object monitors\ngauge",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_deadlocked_monitor{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "java_lang_memorypool_usage_committed",
     "type": "graph",
     "description": "java.lang.management.MemoryUsage (java.lang<type=MemoryPool, name=Code Cache><Usage>committed)",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{instance=~\"$instance\"}",
       "legendFormat": "{{name}} {{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_threads_started_total rate",
     "type": "graph",
     "description": "Started thread count of a JVM\nrate",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_threads_started_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_threads_deadlocked",
     "type": "graph",
     "description": "Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers\ngauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_deadlocked{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "java_lang_memorypool_valid",
     "type": "graph",
     "description": "Valid (java.lang<type=MemoryPool, name=Code Cache><>Valid)",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_valid{instance=~\"$instance\"}",
       "legendFormat": "{{name}} {{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "java_lang_garbagecollector_lastgcinfo_memoryusageaftergc_used",
     "type": "graph",
     "description": "java.lang.management.MemoryUsage (java.lang<type=GarbageCollector, name=ParNew, key=Par Survivor Space><LastGcInfo, memoryUsageAfterGc>used)",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_garbagecollector_lastgcinfo_memoryusageaftergc_used{instance=~\"$instance\"}",
       "legendFormat": "{{name}} {{key}} {{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "java_lang_memorypool_usagethresholdexceeded",
     "type": "graph",
     "description": "UsageThresholdExceeded (java.lang<type=MemoryPool, name=Code Cache><>UsageThresholdExceeded)",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usagethresholdexceeded{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "java_lang_memorypool_collectionusage_used",
     "type": "graph",
     "description": "java.lang.management.MemoryUsage (java.lang<type=MemoryPool, name=Par Eden Space><CollectionUsage>used)",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_collectionusage_used{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "java_lang_memorypool_usage_used",
     "type": "graph",
     "description": "java.lang.management.MemoryUsage (java.lang<type=MemoryPool, name=Code Cache><Usage>used)",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_used{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "java_lang_memorypool_peakusage_committed",
     "type": "graph",
     "description": "java.lang.management.MemoryUsage (java.lang<type=MemoryPool, name=Code Cache><PeakUsage>committed)",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_peakusage_committed{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    },
    {
     "title": "java_lang_memorypool_collectionusagethresholdexceeded",
     "type": "graph",
     "description": "CollectionUsageThresholdExceeded (java.lang<type=MemoryPool, name=Par Eden Space><>CollectionUsageThresholdExceeded)",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_collectionusagethresholdexceeded{instance=~\"$instance\"}",
       "legendFormat": "{{pool}} {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}