---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive
spec:
  image:
    productVersion: 3.1.3
    stackableVersion: "23.4"
  clusterConfig:
    database:
      connString: jdbc:postgresql://postgresql-hive:5432/hive
      user: hive
      password: hive
      dbType: postgres
    s3:
      reference: minio
  metastore:
    roleGroups:
      default:
        config:
          resources:
            storage:
              data:
                storageClass: nfs-client-01
                capacity: 3Gi
        replicas: 1
---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-iceberg
spec:
  image:
    productVersion: 3.1.3
    stackableVersion: "23.4"
  clusterConfig:
    database:
      connString: jdbc:postgresql://postgresql-hive-iceberg:5432/hive
      user: hive
      password: hive
      dbType: postgres
    s3:
      reference: minio
  metastore:
    roleGroups:
      default:
        config:
          resources:
            storage:
              data:
                storageClass: nfs-client-01
                capacity: 3Gi
        replicas: 1
