apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- fluent-operator-crd.yaml
- fluent-operator-clusterRoleBinding.yaml
- fluent-operator-clusterRole.yaml
- fluent-operator-deployment.yaml
- fluent-operator-serviceAccount.yaml

# Change to the namespace you want such as: 
# namespace: fluent

# patchesStrategicMerge:
# To do namespaced RBAC uncomment below
# - scoped/fluent-operator-clusterRole.yaml