yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers: strimzi-kafka-cluster-kafka-bootstrap:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
