apiVersion: v1
kind: Pod
metadata:
  name: log-generator
spec:
  containers:
    - name: log-generator
      image: busybox
      command: ["/bin/sh"]
      args:
        - -c
        - while true; do echo "192.168.2.20 - - [29/Jul/2015:10:27:10 -0300] \"GET /cgi-bin/try/ HTTP/1.0\" 200 3395"; sleep 1;done