apiVersion: fluentbit.fluent.io
kind: ClusterFilter
metadata:
  name: filter-audit-logs
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: auditd
  filters:
  - recordModifier:
      records:
      - node_name ${NODE_NAME}
  - lua:
      script:
        key: auditd.lua
        name: fluent-bit-auditd-config
      call: cb_replace
      timeAsTable: true
  
