apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- auditd-lua-config.yaml
- input-auditd.yaml
- filter-auditd.yaml
- output-auditd-elasticsearch.yaml

# Change to the namespace you want such as: 
# namespace: fluent