apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: mysql-operator
spec:
  secretName: mysql-root-user
  instances: 2
  tlsUseSelfSigned: true
  version: 8.0.31
  router:
    instances: 1
    version: 8.0.31
  datadirVolumeClaimTemplate:
    storageClassName: nfs-client-01
    resources:
      requests:
        storage: 200Gi
