apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-01
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner-nfs-01 # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: nfs-client-kube-prometheus
# provisioner: k8s-sigs.io/nfs-subdir-external-provisioner-kube-prometheus # or choose another name, must match deployment's env PROVISIONER_NAME'
# parameters:
#   archiveOnDelete: "false"  
