{
 "title": "Kafka",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "kafkabroker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"kafkabroker\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "KafkaBroker启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"kafkabroker\",instance=\"$kafkabroker\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线Broker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "活跃的Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "控制节点和从节点",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=~\"kafkabroker\"}-0",
     "legendFormat": "broker"
    }
   ]
  },
  {
   "title": "Topic总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount)"
    }
   ]
  },
  {
   "title": "未消费数据量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total{topic != \"\"}-kafka_server_brokertopicmetrics_bytesout_total{topic != \"\"})"
    }
   ]
  },
  {
   "title": "在线分区数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "离线分区数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=~\"kafkabroker\"})"
    }
   ]
  },
  {
   "title": "ISR扩大速率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_isrexpands_total)"
    }
   ]
  },
  {
   "title": "IO工作处理线程空闲率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_socketserver_networkprocessoravgidlepercent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ISR收缩速率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_isrshrinks_total)"
    }
   ]
  },
  {
   "title": "KafkaBroker堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_max{job='kafkabroker',area='heap'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "控制节点和从节点",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"kafkabroker\"}*100/jvm_memory_bytes_max{area=\"heap\",job=\"kafkabroker\"}",
     "legendFormat": "broker"
    }
   ]
  },
  {
   "title": "消息写入消费速率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic =\"\"}[5m]))",
     "legendFormat": "写入速率"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{topic =\"\"}[5m]))",
     "legendFormat": "消费速率"
    }
   ]
  },
  {
   "title": "网络处理器线程空闲百分比",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(kafka_server_kafkarequesthandlerpool_requesthandleravgidle_percent)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}